---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengist
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opengist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opengist
    spec:
      containers:
        - name: opengist
          image: ghcr.io/thomiceli/opengist
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6157
              name: http
          volumeMounts:
            - mountPath: /app/opengist/opengist
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: opengist-data
